config/routes.rb
Rails.application.routes.draw do
  resources :sites
  resources :trusts
  resources :users
  
  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  match 'access/attempt_login' => 'access#attempt_login', via: [:get, :post]
  get 'access/logout'

  root 'sites#index'

end

app/models/search.rb
class Search < ActiveRecord::Base

	def search_sites
		sites = Site.all

		sites = sites.where(["name LIKE ?", "%#{name}%"]) if name.present?
		sites = sites.where(["city LIKE ?", "%#{city}%"]) if city.present?
		sites = sites.where(["state LIKE ?", "%#{state}%"]) if state.present?
		sites = sites.where(["country LIKE ?", "%#{country}%"]) if country.present?
		sites = sites.where(["start_date >= ?", "%#{start_date}%"]) if start_date.present?
		sites = sites.where(["end_date >= ?", "%#{end_date}%"]) if end_date.present?

		return sites
	end
	
end

app/models/site.rb
class Site < ActiveRecord::Base

	before_create :set_dates
	belongs_to :trust

	scope :keyword_search, lambda {|query| where(["name ILIKE :query OR city ILIKE :query OR state ILIKE :query OR country ILIKE :query", query: "%#{query}%"])}
	scope :name_search, lambda {|name| where(["name ILIKE ?", "%#{name}%"]) if name.present?}
	scope :city_search, lambda {|city| where(["city ILIKE ?", "%#{city}%"]) if city.present?}
	scope :state_search, lambda {|state| where(["state ILIKE ?", "%#{state}%"]) if state.present?}
	scope :country_search, lambda {|country| where(["country ILIKE ?", "%#{country}%"]) if country.present?}
	scope :date_search, lambda {|date_from, date_to| where.not(["? > end_date OR ? < start_date", date_from, date_to])}

  def set_dates
  	self.start_date ||= '1900-01-01'
    self.end_date ||= '2015-01-01'
  end
end

app/models/trust.rb
class Trust < ActiveRecord::Base
	has_many :sites
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password

end

app/controllers/access_controller.rb
class AccessController < ApplicationController

	# before_action :confirm_logged_in, :except => [:login, :attempt_login, :logout]

  def menu
  	#display text & links
  end

  def login
  	#login form
  end

  def attempt_login
    if params[:username].present? && params[:password].present?
      found_user = User.where(:username => params[:username]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end
    end

    if authorized_user
      session[:user_id] = authorized_user.id
      flash[:notice] = 'You are now logged in.'
      redirect_to(sites_path)
    else
      flash.now[:notice] = 'Please try again.'
      render('login')
    end

  end

  def logout
    session[:user_id] = nil
    flash[:notice] = 'You are now logged out.'
    redirect_to(access_login_path)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def confirm_logged_in
    unless session[:user_id]
      flash[:notice] = "Please log in."
      redirect_to(access_login_path)       # redirect_to prevents requested action from running
    end
  end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController

	before_action :confirm_logged_in
	before_action :find_site, only: [:update, :destroy]

	def index

		# search filters

		@sites = Site.all
		@sites = @sites.keyword_search(params[:keyword]) if params[:keyword].present?
		@sites = @sites.name_search(params[:name]) if params[:name].present?
		@sites = @sites.city_search(params[:city]) if params[:city].present?
		@sites = @sites.state_search(params[:state]) if params[:state].present?
		@sites = @sites.country_search(params[:country]) if params[:country].present?

		# date objects

		dateToObj = Date.parse(params[:date_to]) if params[:date_to].present?
		dateFromObj = Date.parse(params[:date_from]) if params[:date_from].present?

		# date filters

		if dateToObj.nil? === false or dateFromObj.nil? === false
			@sites = @sites.date_search(dateFromObj, dateToObj)
		end

		#sort filters

		if params[:sortCriterion].present?
			if true?(params[:reverseOrder])
				@paginatedSites = @sites.order("#{params[:sortCriterion]} DESC, name ASC").page(params[:page]).per(5)
			else
				@paginatedSites = @sites.order("#{params[:sortCriterion]} ASC, name ASC").page(params[:page]).per(5)
			end
		else
			@paginatedSites = @sites.order('trust_id ASC, name ASC').page(params[:page]).per(5)
		end

		# all trusts

		@allTrusts = Trust.all

	    # eligible trusts

		site_ids = @sites.map{|site| site.trust_id}
		unique_site_ids = site_ids.uniq
		@eligibleTrusts = @allTrusts.select{|trust| unique_site_ids.include? trust.id}

	end

	def create
		@site = Site.new(site_params)

		if @site.save
			render json: @site
		else
			render json: @site.errors, status: :unprocessable_entity
		end
	end

	def update
		if @site.update_attributes(site_params)
			render json: @site
		else
			render json: @site.errors, status: :unprocessable_entity
		end
	end

	def destroy
		@site.destroy
		render json: @site
	end

	private

	def find_site
		@site = Site.find(params[:id])
	end

	def site_params
		params.require(:site).permit(:name, :city, :state, :country, :start_date, :end_date, :trust_id, :trust, :site_code)
	end


	def true?(obj)
  		obj.to_s == "true"
	end
end

app/controllers/trusts_controller.rb
class TrustsController < ApplicationController

	before_action :confirm_logged_in

	def index
		@trusts = Trust.all

		respond_to do |format|
	        format.html
	        format.json { render json: @trusts }
	    end
	end

	private

		def trust_params
			params.require(:trust).permit(:name, :location)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :confirm_logged_in
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :username, :password_digest)
    end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/trusts_helper.rb
module TrustsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/access/login.html.erb
<%= react_component 'ExplanatoryModal' %>

<div class="col-sm-3 col-sm-offset-3 login">
  <%= form_tag(access_attempt_login_path, :method => :post) do %>
  <table>
  <tr>
    <th></th>
    <th>
      <% if !flash[:notice].blank? %>
        <div class="col-sm-12">
          <span class="notice"><%= flash[:notice] %></span>  
        </div>
     <% end %>
    </th>
  </tr>
    <tr>
      <td>Username: </td>
      <td><%= text_field_tag(:username, params[:username]) %></td>
    </tr>
    <tr>
      <td>Password: </td>
      <td><%= password_field_tag(:password) %></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td><%= submit_tag("Log In", :class => "btn btn-primary") %></td>
    </tr>
  </table>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default nav-styling">
	<div class="container">
			<a class="navbar-brand menu-bar asbestos-title" href="#"><%= image_tag("flame.png") %> Asbestos Trust Search</a>
			<ul class="nav navbar-nav pull-right">
				<li class="dropdown">
					<a class="dropdown-toggle menu-bar my-account" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-user"></span><strong class="caret"></strong></a>
						<ul class="dropdown-menu dropdown-menu-right dropdown-menu-background">
							<li><a class="email" title="Email webmaster" href="mailto:adam@adamewhite.com?subject=Asbestos%20Trust%20Search%20Feedback"><span class="glyphicon glyphicon-envelope"></span> Send Feedback</a></li>
							<li class="divider"></li>
							<li ><a href="../access/logout"><span class="glyphicon glyphicon-home"></span> Sign Out</a></li>
						</ul>
				</li>	
			</ul>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Asbestos Trust Search</title>
  <%= favicon_link_tag 'favicon-32x32.png' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/sites/index.html.erb
<%= react_component 'AsbestosTrustSearchApp', render(template: 'sites/index.json.jbuilder', prerender: true) %>